"""add_twitter_discovery_tables

Revision ID: 12ae452b6bb0
Revises: 7305462420eb
Create Date: 2026-05-21 14:35:27.562417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ae452b6bb0'
down_revision: Union[str, Sequence[str], None] = '7305462420eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('influence_score', sa.Float(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencer_metrics_username'), 'influencer_metrics', ['username'], unique=True)
    op.create_table('trend_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(length=255), nullable=False),
    sa.Column('cluster_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_clusters_cluster_name'), 'trend_clusters', ['cluster_name'], unique=False)
    op.create_table('twitter_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('emotional_score', sa.Float(), nullable=False),
    sa.Column('retention_score', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_stage', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_trends_author'), 'twitter_trends', ['author'], unique=False)
    op.create_index(op.f('ix_twitter_trends_content_hash'), 'twitter_trends', ['content_hash'], unique=False)
    op.create_index(op.f('ix_twitter_trends_processing_status'), 'twitter_trends', ['processing_status'], unique=False)
    op.create_index(op.f('ix_twitter_trends_tweet_id'), 'twitter_trends', ['tweet_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_trends_tweet_id'), table_name='twitter_trends')
    op.drop_index(op.f('ix_twitter_trends_processing_status'), table_name='twitter_trends')
    op.drop_index(op.f('ix_twitter_trends_content_hash'), table_name='twitter_trends')
    op.drop_index(op.f('ix_twitter_trends_author'), table_name='twitter_trends')
    op.drop_table('twitter_trends')
    op.drop_index(op.f('ix_trend_clusters_cluster_name'), table_name='trend_clusters')
    op.drop_table('trend_clusters')
    op.drop_index(op.f('ix_influencer_metrics_username'), table_name='influencer_metrics')
    op.drop_table('influencer_metrics')
    # ### end Alembic commands ###
