"""Create job queue tables

Revision ID: 71473a23179a
Revises: 
Create Date: 2026-05-20 16:47:26.237725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71473a23179a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_generations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('script_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('voice_name', sa.String(), nullable=False),
    sa.Column('preset_name', sa.String(), nullable=True),
    sa.Column('emotional_tone', sa.String(), nullable=True),
    sa.Column('narration_style', sa.String(), nullable=True),
    sa.Column('raw_audio_path', sa.String(), nullable=True),
    sa.Column('processed_audio_path', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'GENERATED', 'PROCESSING', 'COMPLETED', 'ARCHIVED', 'FAILED', 'DELETED', name='audiostatus'), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_generations_id'), 'audio_generations', ['id'], unique=False)
    op.create_index(op.f('ix_audio_generations_script_id'), 'audio_generations', ['script_id'], unique=False)
    op.create_table('caption_animation_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('animation_name', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animation_name')
    )
    op.create_table('caption_styles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('style_name', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_name')
    )
    op.create_table('dead_letter_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_job_id', sa.String(length=255), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_jobs_id'), 'dead_letter_jobs', ['id'], unique=False)
    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_logs_task_name'), 'generation_logs', ['task_name'], unique=False)
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('assigned_worker', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_jobs_id'), 'pipeline_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_workflow_id'), 'pipeline_jobs', ['workflow_id'], unique=False)
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_logs_stage'), 'processing_logs', ['stage'], unique=False)
    op.create_index(op.f('ix_processing_logs_status'), 'processing_logs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_logs_topic_id'), 'processing_logs', ['topic_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_name'), 'prompt_versions', ['prompt_name'], unique=False)
    op.create_table('reddit_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('comments_count', sa.Float(), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('emotional_score', sa.Float(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_stage', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_nsfw', sa.Boolean(), nullable=False),
    sa.Column('permalink', sa.String(length=500), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_topics_content_hash'), 'reddit_topics', ['content_hash'], unique=False)
    op.create_index(op.f('ix_reddit_topics_processing_status'), 'reddit_topics', ['processing_status'], unique=False)
    op.create_index(op.f('ix_reddit_topics_reddit_id'), 'reddit_topics', ['reddit_id'], unique=True)
    op.create_index(op.f('ix_reddit_topics_subreddit'), 'reddit_topics', ['subreddit'], unique=False)
    op.create_table('video_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('niche', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('aspect_ratio', sa.String(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_table('worker_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_name', sa.String(length=255), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('active_jobs', sa.JSON(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_states_id'), 'worker_states', ['id'], unique=False)
    op.create_index(op.f('ix_worker_states_worker_name'), 'worker_states', ['worker_name'], unique=True)
    op.create_table('caption_render_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('style_id', sa.String(), nullable=True),
    sa.Column('animation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animation_id'], ['caption_animation_profiles.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['caption_styles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_name')
    )
    op.create_table('generated_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('full_script', sa.Text(), nullable=False),
    sa.Column('duration_target', sa.Float(), nullable=False),
    sa.Column('estimated_duration', sa.Float(), nullable=False),
    sa.Column('provider_used', sa.String(length=100), nullable=False),
    sa.Column('hook_type', sa.String(length=50), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['reddit_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('failure_stage', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('worker_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_failures_id'), 'job_failures', ['id'], unique=False)
    op.create_table('reddit_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('reddit_comment_id', sa.String(length=20), nullable=False),
    sa.Column('comment_body', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('replies_count', sa.Float(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['reddit_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_comments_reddit_comment_id'), 'reddit_comments', ['reddit_comment_id'], unique=True)
    op.create_table('video_clips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('clip_start', sa.Float(), nullable=True),
    sa.Column('clip_end', sa.Float(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('render_id', sa.String(), nullable=True),
    sa.Column('usage_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['video_assets.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['generated_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_timelines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('narration_duration', sa.Float(), nullable=True),
    sa.Column('total_scene_duration', sa.Float(), nullable=True),
    sa.Column('timeline_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['generated_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('profanity_score', sa.Float(), nullable=False),
    sa.Column('duplicate_score', sa.Float(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('failures_json', sa.JSON(), nullable=True),
    sa.Column('duration_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['generated_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_validations_script_id'), 'script_validations', ['script_id'], unique=False)
    op.create_table('subtitle_generations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('audio_generation_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='subtitlestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_generation_id'], ['audio_generations.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['generated_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formatted_subtitles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subtitle_generation_id', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('output_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_generation_id'], ['subtitle_generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timeline_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('pacing_style', sa.String(), nullable=True),
    sa.Column('transition_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['video_assets.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['scene_timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtitle_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subtitle_generation_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('word_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_generation_id'], ['subtitle_generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_timestamps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subtitle_generation_id', sa.String(), nullable=True),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_generation_id'], ['subtitle_generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtitle_exports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subtitle_id', sa.String(), nullable=True),
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_id'], ['formatted_subtitles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtitle_exports')
    op.drop_table('word_timestamps')
    op.drop_table('subtitle_segments')
    op.drop_table('scene_segments')
    op.drop_table('formatted_subtitles')
    op.drop_table('subtitle_generations')
    op.drop_index(op.f('ix_script_validations_script_id'), table_name='script_validations')
    op.drop_table('script_validations')
    op.drop_table('scene_timelines')
    op.drop_table('asset_usage_logs')
    op.drop_table('video_clips')
    op.drop_index(op.f('ix_reddit_comments_reddit_comment_id'), table_name='reddit_comments')
    op.drop_table('reddit_comments')
    op.drop_index(op.f('ix_job_failures_id'), table_name='job_failures')
    op.drop_table('job_failures')
    op.drop_table('generated_scripts')
    op.drop_table('caption_render_profiles')
    op.drop_index(op.f('ix_worker_states_worker_name'), table_name='worker_states')
    op.drop_index(op.f('ix_worker_states_id'), table_name='worker_states')
    op.drop_table('worker_states')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_reddit_topics_subreddit'), table_name='reddit_topics')
    op.drop_index(op.f('ix_reddit_topics_reddit_id'), table_name='reddit_topics')
    op.drop_index(op.f('ix_reddit_topics_processing_status'), table_name='reddit_topics')
    op.drop_index(op.f('ix_reddit_topics_content_hash'), table_name='reddit_topics')
    op.drop_table('reddit_topics')
    op.drop_index(op.f('ix_prompt_versions_prompt_name'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_processing_logs_topic_id'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_status'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_stage'), table_name='processing_logs')
    op.drop_table('processing_logs')
    op.drop_index(op.f('ix_pipeline_jobs_workflow_id'), table_name='pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_jobs_id'), table_name='pipeline_jobs')
    op.drop_table('pipeline_jobs')
    op.drop_index(op.f('ix_generation_logs_task_name'), table_name='generation_logs')
    op.drop_table('generation_logs')
    op.drop_index(op.f('ix_dead_letter_jobs_id'), table_name='dead_letter_jobs')
    op.drop_table('dead_letter_jobs')
    op.drop_table('caption_styles')
    op.drop_table('caption_animation_profiles')
    op.drop_index(op.f('ix_audio_generations_script_id'), table_name='audio_generations')
    op.drop_index(op.f('ix_audio_generations_id'), table_name='audio_generations')
    op.drop_table('audio_generations')
    # ### end Alembic commands ###
